### ISSUE TITLE
README

### ISSUE THREAD

**Issue by valentt** [maxwolffe/APSwag#3]
Can you please add explanation in README what this code does, and why do you have IP and MAC adresses hardcoded in your code?

**Comment by maxwolffe** [comment]
Hi Valentt, thanks for the issue, development had been stymied for a bit thanks to school. I've updated the README a bit, feel free to point out things that you think it's missing. IP and MAC addresses are hardcoded right now to allow for testing. They're copied from the cloyne/network repository, as the project is primarily for the Cloyne network at the moment.
