### ISSUE TITLE
Status people!

### ISSUE THREAD

**Issue by mitar** [maxwolffe/APSwag#6]

**Comment by maxwolffe** [comment]
I'm the worst. Plan is to have something useful to show you by May 13, then something psuedo final by May 15.

**Comment by mitar** [comment]
You are. And Jake?

**Comment by JakeLerner** [comment]
I have something pretty useful slash close to what I initially planned to
do now.  I might work on it a bit more this weekend if I have time. Max I
can also help you some if you want.

**Comment by mitar** [comment]
Let's help each other to make things be done. :-) So, when will you be working? :-)
